import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/footer/Footer";
import "../globals.css";
import { LanguageProvider } from "@/utils/i18n";
import { headers } from "next/headers";
import { getLanguageFromPath } from "@/utils/helpers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const pathname = (await headersList).get("x-url") || "";
  const language = getLanguageFromPath(pathname);

  return (
    <LanguageProvider language={getLanguageFromPath(language)}>
      <html lang={language}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
        >
          <main className="mb-footer-height">{children}</main>
          <div className="fixed inset-x-0 bottom-0 h-footer-height bg-background">
            <Footer />
          </div>
        </body>
      </html>
    </LanguageProvider>
  );
}
